NNConf:
    layers:
        - name: Input
          properties:
              - {Width: 784, Channels: 1}
        - name: Encoder
          properties:
              - {Width: 256, Activation: relu}
              - {Width: 128, Activation: relu}
              - {Width: 64, Activation: relu}
        - name: MultiNormalParams
          properties:
              - {Width: 16, Activation: relu}
              - {Width: 16, Activation: relu}
        - name: Decoder
          properties:
              - {Width: 64, Activation: relu}
              - {Width: 128, Activation: relu}
              - {Width: 256, Activation: relu}
        - name: Output
          properties:
              - {Width: 784, Channels: 1}
seed: 6

